### ISSUE TITLE
No longer testable

### ISSUE THREAD

**Issue by davedoesdev** [codeactual/apidox#14]
```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t git://github.com/codeactual/node-component-grunt.git
npm ERR! 
npm ERR! fatal: remote error: 
npm ERR!   Repository not found.
```

Did you delete `node-component-grunt`?

**Comment by codeactual** [comment]
I've restored the repo I deleted.

**Comment by davedoesdev** [comment]
Thanks. Any chance of publishing it?

**Comment by codeactual** [comment]
If there are no blockers (like that error), I'd rather not spend any more time on it keeping that package going.

Rationale: the component dependency should just get removed altogether since [that project is deprecated](https://github.com/componentjs/component) and I don't think anything in apidox really depends on it.
